# Generated by Django 5.2.11 on 2026-02-14 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="KnowledgeCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Animal", "Animal"),
                            ("Plant", "Plant"),
                            ("Object", "Object"),
                            ("Other", "Other"),
                        ],
                        default="Other",
                        max_length=50,
                    ),
                ),
                ("summary", models.TextField()),
                ("description", models.TextField(blank=True)),
                (
                    "tags",
                    models.CharField(help_text="Comma separated tags", max_length=300),
                ),
                (
                    "keywords",
                    models.CharField(
                        blank=True, help_text="Optional extra keywords", max_length=500
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CardImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="knowledge_cards/%Y/%m/%d")),
                ("original_filename", models.CharField(max_length=255)),
                ("average_hash", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="cards.knowledgecard",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
