# Generated by Django 6.0.3 on 2026-03-26 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardimage',
            name='signature',
            field=models.TextField(blank=True, default=''),
        ),
    ]
